name: Antalya Ä°hale Bot

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Restore cache (seen)
        uses: actions/cache@v4
        with:
          path: .cache
          key: antalya-ihale-seen-v5
          restore-keys: |
            antalya-ihale-seen-v5

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests certifi cloudscraper

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_IDS: ${{ secrets.CHAT_IDS }}
          DEBUG: "1"
          MAX_PAGES: "6"
          MAX_SEND_PER_RUN: "6"
        run: |
          python bot.py
